remote_theme: pages-themes/cayman@v0.2.0
title: "NEF to JPG Converter"
description: "A modern Python tool for converting Nikon NEF raw files to JPEG format with batch processing and dual interface support"
url: "https://r4inx.github.io"
baseurl: "/nef-to-jpg"

author: "r4inX"
github_username: r4inX

repository: "r4inX/nef-to-jpg"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .venv/
  - __pycache__/
  - "*.pyc"
  - .pytest_cache/
  - .coverage
  - .mypy_cache/
  - build/
  - dist/
  - "*.egg-info/"
  - tests/
  - src/
  - photoconverter/
  - requirements*.txt
  - setup.cfg
  - pyproject.toml
  - MANIFEST.in
  - nef_converter.py